import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="p-6 bg-gray-100 overflow-auto">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-600 mb-6">
        Last updated: September 12, 2024
      </p>

      <p className="mb-4 text-gray-700">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>

      <p className="mb-4 text-gray-700">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{" "}
        <a
          href="https://www.privacypolicies.com/privacy-policy-generator/"
          target="_blank"
          className="text-blue-600 underline"
        >
          Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
      <p className="mb-4 text-gray-700">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold mb-3">Definitions</h3>
      <p className="mb-4 text-gray-700">
        For the purposes of this Privacy Policy:
      </p>

      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>
          <span className="font-semibold">Account</span> means a unique account
          created for You to access our Service or parts of our Service.
        </li>
        <li>
          <span className="font-semibold">Affiliate</span> means an entity that
          controls, is controlled by, or is under common control with a party,
          where "control" means ownership of 50% or more of the shares, equity
          interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <span className="font-semibold">Company</span> (referred to as either
          "the Company", "We", "Us" or "Our" in this Agreement) refers to
          pdfdialogue.
        </li>
        <li>
          <span className="font-semibold">Cookies</span> are small files that
          are placed on Your computer, mobile device, or any other device by a
          website, containing the details of Your browsing history on that
          website among its many uses.
        </li>
        <li>
          <span className="font-semibold">Country</span> refers to: Maharashtra,
          India
        </li>
        <li>
          <span className="font-semibold">Device</span> means any device that
          can access the Service such as a computer, a cellphone, or a digital
          tablet.
        </li>
        <li>
          <span className="font-semibold">Personal Data</span> is any
          information that relates to an identified or identifiable individual.
        </li>
        <li>
          <span className="font-semibold">Service</span> refers to the Website.
        </li>
        <li>
          <span className="font-semibold">Service Provider</span> means any
          natural or legal person who processes the data on behalf of the
          Company. It refers to third-party companies or individuals employed by
          the Company to facilitate the Service, to provide the Service on
          behalf of the Company, to perform services related to the Service, or
          to assist the Company in analyzing how the Service is used.
        </li>
        <li>
          <span className="font-semibold">
            Third-party Social Media Service
          </span>{" "}
          refers to any website or any social network website through which a
          User can log in or create an account to use the Service.
        </li>
        <li>
          <span className="font-semibold">Usage Data</span> refers to data
          collected automatically, either generated by the use of the Service or
          from the Service infrastructure itself (for example, the duration of a
          page visit).
        </li>
        <li>
          <span className="font-semibold">Website</span> refers to pdfdialogue,
          accessible from{" "}
          <a
            href="https://www.pdfdialogue.com/"
            className="text-blue-600 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://www.pdfdialogue.com/
          </a>
        </li>
        <li>
          <span className="font-semibold">You</span> means the individual
          accessing or using the Service, or the company, or other legal entity
          on behalf of which such individual is accessing or using the Service,
          as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-semibold mb-3">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
      <p className="mb-4 text-gray-700">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>

      <ul className="list-disc list-inside mb-6 space-y-2">
        <li className="text-gray-700">Email address</li>
        <li className="text-gray-700">First name and last name</li>
        <li className="text-gray-700">Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
      <p className="mb-4 text-gray-700">
        Usage Data is collected automatically when using the Service.
      </p>
      {/* More content can follow here */}
    </div>
  );
};

export default PrivacyPolicy;
